name: JavaFlow CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Generate test coverage report
        run: ./gradlew jacocoTestReport

      - name: Verify test coverage
        run: ./gradlew jacocoTestCoverageVerification

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            build/reports/tests/
            build/reports/jacoco/
            build/reports/checkstyle/