name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
      next_version:
        description: 'Next development version (e.g., 1.1.0-SNAPSHOT)'
        required: true

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Update to release version
        run: |
          RELEASE_VERSION="${{ github.event.inputs.release_version }}"
          sed -i "s/version = '.*'/version = '$RELEASE_VERSION'/g" build.gradle
          echo "Updated build.gradle to release version $RELEASE_VERSION"
      
      - name: Build and test with release version
        run: ./gradlew clean build
      
      - name: Commit release version
        run: |
          git add build.gradle
          git commit -m "chore: prepare release ${{ github.event.inputs.release_version }}"
      
      - name: Create release tag
        run: git tag -a v${{ github.event.inputs.release_version }} -m "Release ${{ github.event.inputs.release_version }}"
      
      - name: Update to next development version
        run: |
          NEXT_VERSION="${{ github.event.inputs.next_version }}"
          sed -i "s/version = '.*'/version = '$NEXT_VERSION'/g" build.gradle
          echo "Updated build.gradle to next development version $NEXT_VERSION"
      
      - name: Commit next development version
        run: |
          git add build.gradle
          git commit -m "chore: prepare for next development version ${{ github.event.inputs.next_version }}"
      
      - name: Push changes
        run: |
          git push
          git push --tags
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.release_version }}
          name: Release ${{ github.event.inputs.release_version }}
          draft: false
          prerelease: false
          generate_release_notes: true