name: Publish Snapshot

on:
  workflow_dispatch:

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Verify snapshot version
        run: |
          VERSION=$(grep -oP "version\s*=\s*'\K[^']+" build.gradle)
          if [[ $VERSION != *"-SNAPSHOT"* ]]; then
            echo "Error: Current version '$VERSION' in build.gradle is not a snapshot version."
            echo "Please ensure the version in build.gradle ends with '-SNAPSHOT' before running this workflow."
            exit 1
          fi
          echo "Publishing version: $VERSION"

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Publish Snapshot to Maven Central
        run: ./gradlew publishToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SONATYPE_HOST: S01
          SONATYPE_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}